mediamonks_media_image:
    path:  /media/image/{id}/{width}/{height}
    defaults: {_controller: MediaMonksSonataMediaBundle:Media:imageRedirect}
    methods:  [GET]
    requirements:
        id: \d+
