mediamonks_media_autocomplete:
    path: /media/autocomplete
    defaults: {_controller: mediamonks.sonata_media.controller.helper:getAutocompleteItemsAction}
    methods:  [GET]

mediamonks_media_batch:
    path: /media/batch/list
    defaults: {_controller: mediamonks.sonata_media.controller.batch:listAction}
    methods:  [GET]

mediamonks_media_batch_upload:
    path: /media/batch/upload
    defaults: {_controller: mediamonks.sonata_media.controller.batch:uploadAction}
    methods:  [POST]
