parameters:
    mediamonks.sonata_media.admin.media.class: 'MediaMonks\SonataMediaBundle\Admin\MediaAdmin'
    mediamonks.sonata_media.provider.image.class: 'MediaMonks\SonataMediaBundle\Provider\ImageProvider'
    mediamonks.sonata_media.provider.youtube.class: 'MediaMonks\SonataMediaBundle\Provider\YouTubeProvider'
    mediamonks.sonata_media.provider.vimeo.class: 'MediaMonks\SonataMediaBundle\Provider\VimeoProvider'
    mediamonks.sonata_media.provider.file.class: 'MediaMonks\SonataMediaBundle\Provider\FileProvider'
    mediamonks.sonata_media.provider.soundcloud.class: 'MediaMonks\SonataMediaBundle\Provider\SoundCloudProvider'
    mediamonks.sonata_media.provider.pool.class: 'MediaMonks\SonataMediaBundle\Provider\ProviderPool'
    mediamonks.sonata_media.twig.extension.class: 'MediaMonks\SonataMediaBundle\Twig\Extension\MediaExtension'
    mediamonks.sonata_media.glide.server.class: 'League\Glide\Server'
    mediamonks.sonata_media.glide.server.factory.class: 'League\Glide\ServerFactory'
    mediamonks.sonata_media.handler.signature_parameter_handler.class: 'MediaMonks\SonataMediaBundle\Handler\SignatureParameterHandler'
    mediamonks.sonata_media.generator.url_generator.class: 'MediaMonks\SonataMediaBundle\Generator\UrlGenerator'
    mediamonks.sonata_media.generator.filename_generator.default.class: 'MediaMonks\SonataMediaBundle\Generator\DefaultFilenameGenerator'
    mediamonks.sonata_media.generator.image.class: 'MediaMonks\SonataMediaBundle\Generator\ImageGenerator'
    mediamonks.sonata_media.utility.image.class: 'MediaMonks\SonataMediaBundle\Utility\ImageUtility'
    mediamonks.sonata_media.utility.download.class: 'MediaMonks\SonataMediaBundle\Utility\DownloadUtility'
    mediamonks.sonata_media.utility.event_listener.menu_builder.class: 'MediaMonks\SonataMediaBundle\EventListener\MenuBuilderListener'
    mediamonks.sonata_media.form.type.media_autocomplete.class: 'MediaMonks\SonataMediaBundle\Form\Type\MediaAutocompleteType'

services:
    mediamonks.sonata_media.admin.media:
        class: '%mediamonks.sonata_media.admin.media.class%'
        arguments: [~, 'MediaMonks\SonataMediaBundle\Entity\Media', 'MediaMonksSonataMediaBundle:MediaAdmin', '@mediamonks.sonata_media.provider.pool']
        tags:
            - { name: sonata.admin, manager_type: orm, label: Media, group: "Media" }
        calls:
            - [ setTemplate, ['outer_list_rows_mosaic', 'MediaMonksSonataMediaBundle:MediaAdmin:outer_list_rows_mosaic.html.twig']]
            - [ setTemplate, ['edit', 'MediaMonksSonataMediaBundle:MediaAdmin:edit.html.twig']]

    mediamonks.sonata_media.provider.pool:
        class: '%mediamonks.sonata_media.provider.pool.class%'

    mediamonks.sonata_media.provider.image:
        class: '%mediamonks.sonata_media.provider.image.class%'
        tags:
            - { name: sonata_media.provider }

    mediamonks.sonata_media.provider.youtube:
        class: '%mediamonks.sonata_media.provider.youtube.class%'
        tags:
            - { name: sonata_media.provider }

    mediamonks.sonata_media.provider.vimeo:
            class: '%mediamonks.sonata_media.provider.vimeo.class%'
            tags:
                - { name: sonata_media.provider }

    mediamonks.sonata_media.provider.file:
        class: '%mediamonks.sonata_media.provider.file.class%'
        arguments:
            - []
        tags:
            - { name: sonata_media.provider }

    mediamonks.sonata_media.provider.soundcloud:
        class: '%mediamonks.sonata_media.provider.soundcloud.class%'
        tags:
            - { name: sonata_media.provider }

    mediamonks.sonata_media.twig.extension:
        class: '%mediamonks.sonata_media.twig.extension.class%'
        arguments:
            - '@mediamonks.sonata_media.provider.pool'
            - '@mediamonks.sonata_media.generator.url_generator'
        tags:
            - { name: twig.extension }

    mediamonks.sonata_media.glide.server:
        class: '%mediamonks.sonata_media.glide.server.class%'
        factory: ['%mediamonks.sonata_media.glide.server.factory.class%', 'create']
        arguments:
            - ~

    mediamonks.sonata_media.handler.signature_parameter_handler:
        class: '%mediamonks.sonata_media.handler.signature_parameter_handler.class%'
        arguments:
            - '%secret%'

    mediamonks.sonata_media.generator.url_generator:
        class: '%mediamonks.sonata_media.generator.url_generator.class%'
        arguments:
            - '@router'
            - '@mediamonks.sonata_media.handler.signature_parameter_handler'
            - 'mediamonks_media_image'

    mediamonks.sonata_media.generator.filename_generator.default:
        class: '%mediamonks.sonata_media.generator.filename_generator.default.class%'

    mediamonks.sonata_media.generator.image:
        class: '%mediamonks.sonata_media.generator.image.class%'
        arguments:
            - '@mediamonks.sonata_media.glide.server'
            - '@mediamonks.sonata_media.generator.filename_generator.default'

    mediamonks.sonata_media.utility.image:
        class: '%mediamonks.sonata_media.utility.image.class%'
        arguments:
            - '@mediamonks.sonata_media.handler.signature_parameter_handler'
            - '@mediamonks.sonata_media.generator.image'
            - ~
            - ~
            - []

    mediamonks.sonata_media.utility.download:
        class: '%mediamonks.sonata_media.utility.download.class%'
        arguments:
            - ~

    mediamonks.sonata_media.utility.event_listener.menu_builder:
        class: '%mediamonks.sonata_media.utility.event_listener.menu_builder.class%'
        arguments:
            - '@mediamonks.sonata_media.provider.pool'
            - '@translator'
        tags:
            - { name: kernel.event_listener, event: sonata.admin.event.configure.menu.sidebar, method: addMenuItems }

    mediamonks.sonata_media.form.type.media_autocomplete:
        class: '%mediamonks.sonata_media.form.type.media_autocomplete.class%'
        arguments:
            - '@templating'
        tags:
            - { name: form.type }
