parameters:
    mediamonks.media.admin.media.class: 'MediaMonks\SonataMediaBundle\Admin\MediaAdmin'
    mediamonks.media.provider.image.class: 'MediaMonks\SonataMediaBundle\Provider\ImageProvider'
    mediamonks.media.provider.youtube.class: 'MediaMonks\SonataMediaBundle\Provider\YouTubeProvider'
    mediamonks.media.provider.pool.class: 'MediaMonks\SonataMediaBundle\Provider\ProviderPool'
    mediamonks.media.twig.extension.class: 'MediaMonks\SonataMediaBundle\Twig\Extension\MediaExtension'
    mediamonks.media.helper.parameter.class: 'MediaMonks\SonataMediaBundle\Helper\Parameter'
    mediamonks.media.helper.thumbnail.class: 'MediaMonks\SonataMediaBundle\Helper\Thumbnail'
    mediamonks.media.helper.controller.class: 'MediaMonks\SonataMediaBundle\Helper\Controller'

services:
    mediamonks.media.admin.media:
        class: '%mediamonks.media.admin.media.class%'
        arguments: [~, 'MediaMonks\SonataMediaBundle\Entity\Media', 'MediaMonksSonataMediaBundle:MediaAdmin', '@mediamonks.media.provider.pool']
        tags:
            - { name: sonata.admin, manager_type: orm, label: Media }
        calls:
            - [ setTemplate, ['outer_list_rows_mosaic', 'MediaMonksSonataMediaBundle:MediaAdmin:outer_list_rows_mosaic.html.twig']]
            - [ setTemplate, ['edit', 'MediaMonksSonataMediaBundle:MediaAdmin:edit.html.twig']]

    mediamonks.media.provider.pool:
        class: '%mediamonks.media.provider.pool.class%'

    mediamonks.media.provider.image:
        class: '%mediamonks.media.provider.image.class%'
        arguments:
            - ~

    mediamonks.media.provider.youtube:
        class: '%mediamonks.media.provider.youtube.class%'
        arguments:
            - ~

    mediamonks.media.twig.extension:
        class: '%mediamonks.media.twig.extension.class%'
        arguments:
            - '@mediamonks.media.provider.pool'
            - '@mediamonks.media.helper.parameter'
        tags:
            - { name: twig.extension }

    mediamonks.media.glide.server:
        class: League\Glide\Server
        factory: ['League\Glide\ServerFactory', 'create']
        arguments:
            - ~

    mediamonks.media.helper.parameter:
        class: '%mediamonks.media.helper.parameter.class%'
        arguments:
            - '@router.default'
            -
              public: 'mediamonks_media_thumbnail'
              private: 'admin_mediamonks_core_media_thumbnail'
            - '%secret%'

    mediamonks.media.helper.thumbnail:
        class: '%mediamonks.media.helper.thumbnail.class%'
        arguments:
            - '@mediamonks.media.glide.server'

    mediamonks.media.helper.controller:
        class: '%mediamonks.media.helper.controller.class%'
        arguments:
            - '@mediamonks.media.helper.parameter'
            - '@mediamonks.media.helper.thumbnail'
            - ~
            - ~
