services:
    mediamonks.media.admin.media:
        class: MediaMonks\MediaBundle\Admin\MediaAdmin
        arguments: [~, 'MediaMonks\MediaBundle\Entity\Media', 'MediaMonksMediaBundle:MediaAdmin', '@mediamonks.media.provider.pool']
        tags:
            - { name: sonata.admin, manager_type: orm, label: Media }
        calls:
            - [ setTemplate, ['outer_list_rows_mosaic', 'MediaMonksMediaBundle:MediaAdmin:outer_list_rows_mosaic.html.twig']]
            - [ setTemplate, ['edit', 'MediaMonksMediaBundle:MediaAdmin:edit.html.twig']]

    mediamonks.media.provider.image:
        class: MediaMonks\MediaBundle\Provider\ImageProvider
        arguments:
            - '@oneup_flysystem.default_filesystem'
        tags:
            - { name: mediamonks.media.provider }

    mediamonks.media.provider.youtube:
        class: MediaMonks\MediaBundle\Provider\YouTubeProvider
        arguments:
            - '@oneup_flysystem.default_filesystem'
        tags:
            - { name: mediamonks.media.provider }

    mediamonks.media.provider.pool:
        class: MediaMonks\MediaBundle\Provider\ProviderPool
        calls:
            - [addProvider, ['mediamonks.media.provider.image', '@mediamonks.media.provider.image']]
            - [addProvider, ['mediamonks.media.provider.youtube', '@mediamonks.media.provider.youtube']]

    mediamonks.media.twig.extension:
        class: MediaMonks\MediaBundle\Twig\Extension\MediaExtension
        arguments:
            - '@mediamonks.media.provider.pool'
            - '@mediamonks.media.helper.parameter'
        tags:
            - { name: twig.extension }

    mediamonks.media.glide.server:
        class: League\Glide\Server
        factory: [League\Glide\ServerFactory, create]
        arguments:
          ~:
              source: '@oneup_flysystem.default_filesystem'
              cache: '@oneup_flysystem.default_filesystem'

    mediamonks.media.helper.parameter:
        class: MediaMonks\MediaBundle\Helper\Parameter
        arguments:
            - '@router.default'
            -
              public: 'mediamonks_media_thumbnail'
              private: 'admin_mediamonks_core_media_thumbnail'
            - '%secret%'

    mediamonks.media.helper.thumbnail:
        class: MediaMonks\MediaBundle\Helper\Thumbnail
        arguments:
            - '@mediamonks.media.glide.server'

    mediamonks.media.helper.controller:
        class: MediaMonks\MediaBundle\Helper\Controller
        arguments:
            - '@mediamonks.media.helper.parameter'
            - '@mediamonks.media.helper.thumbnail'
            - 'http://localhost/mediamonks-sonata-media/web/data/'
