mediamonks_media_image:
    path:  /media/image/{id}/{width}/{height}
    defaults: {_controller: MediaMonksSonataMediaBundle:Media:imageRedirect}
    methods:  [GET]
    requirements:
        id: \d+

mediamonks_media_download:
    path:  /media/download/{id}
    defaults: {_controller: MediaMonksSonataMediaBundle:Media:download}
    methods:  [GET]
    requirements:
        id: \d+
